#!/usr/bin/env php
<?php
require(__DIR__ . '/vendor/autoload.php');

defined('YII_DEBUG') or define('YII_DEBUG', (boolean)getenv('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));

require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = \common\config\ConfigLoader::load('console');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
