#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

defined('YII_DEBUG') || define('YII_DEBUG', (bool)getenv('YII_DEBUG'));
defined('YII_ENV') || define('YII_ENV', getenv('YII_ENV'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = \common\config\ConfigLoader::load('console');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
